name: build

on:
  push:
    branches:
      - master
jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: bump version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git fetch --tags
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "latest tag: $latest_tag"
          new_tag=$(echo $latest_tag | sed s/v// | awk -F. -v a="$1" -v b="$2" -v c="$3" '{printf("%d.%d.%d", $1+a, $2+b , $3+1)}')
          echo "new tag: v$new_tag"

          ## update python version
          cat << EOF > src/aws_assume_role/version.py
          #! /usr/bin/env python

          __version__ = '$new_tag'

          EOF

          git commit --reuse-message=HEAD@{1} src/aws_assume_role/version.py || echo "No changes to commit"
          git push origin
          git tag v$new_tag
          git push origin v$new_tag
  publish-package:
    needs: bump-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - uses: dschep/install-pipenv-action@v1
      - name: Install dependencies
        run: |
          pipenv install --dev
      - name: create python package
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git fetch --tags
          git pull
          pipenv run python setup.py sdist bdist_wheel
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
  update-brew:
    needs: publish-package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - uses: dschep/install-pipenv-action@v1
      - name: publish brew
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          pipenv run pip install homebrew-pypi-poet
          pipenv run pip install bc-onelogin-aws-assume-role -U
          git pull
          pipenv run poet -f bc-onelogin-aws-assume-role > HomebrewFormula/bc-onelogin-aws-assume-role.rb
          git commit --reuse-message=HEAD@{1} HomebrewFormula/bc-onelogin-aws-assume-role.rb || echo "No brew changes to commit"
          git push origin